# Generated by Django 4.2.27 on 2026-01-24 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Giveaway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('giveaway_type', models.CharField(choices=[('standard', 'Standard (Same Link for Everyone)'), ('unique', 'Unique (One Code Per User)')], max_length=20)),
                ('requirement_type', models.CharField(choices=[('none', 'No Requirement'), ('manual_approval', 'Manual Verification (Screenshot/Proof)')], max_length=20)),
                ('static_content', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TelegramBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('token', models.CharField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=50)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='giveaway_engine.telegrambot')),
            ],
            options={
                'unique_together': {('bot', 'chat_id')},
            },
        ),
        migrations.CreateModel(
            name='NewsUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='giveaway_engine.telegrambot')),
            ],
        ),
        migrations.CreateModel(
            name='GiveawayItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=500)),
                ('is_used', models.BooleanField(default=False)),
                ('claimed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='giveaway_engine.telegramuser')),
                ('giveaway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='giveaway_engine.giveaway')),
            ],
        ),
        migrations.CreateModel(
            name='GiveawayAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_proof', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved & Sent'), ('rejected', 'Rejected')], default='approved', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('giveaway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='giveaway_engine.giveaway')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='giveaway_engine.telegramuser')),
            ],
        ),
        migrations.AddField(
            model_name='giveaway',
            name='bot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='giveaway_engine.telegrambot'),
        ),
    ]
