# Generated by Django 4.2.27 on 2026-01-24 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giveaway_engine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegrambot',
            name='description',
            field=models.TextField(blank=True, help_text='What the bot can do (shown on start).', null=True),
        ),
        migrations.AddField(
            model_name='telegrambot',
            name='short_description',
            field=models.TextField(blank=True, help_text='Shown in chat info/preview.', null=True),
        ),
    ]
