# Generated by Django 4.2.27 on 2026-01-24 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('giveaway_engine', '0002_telegrambot_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegrambot',
            name='description',
            field=models.TextField(blank=True, help_text='what the bot can do', null=True),
        ),
        migrations.AlterField(
            model_name='telegrambot',
            name='short_description',
            field=models.TextField(blank=True, help_text='shown in chat info/preview', null=True),
        ),
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('content', models.TextField(help_text="Variables: {content} (the code/link), {name} (user's name)")),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='giveaway_engine.telegrambot')),
            ],
        ),
        migrations.AddField(
            model_name='giveaway',
            name='approval_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='giveaway_engine.messagetemplate'),
        ),
    ]
