# Generated by Django 4.2.27 on 2026-01-24 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giveaway_engine', '0003_alter_telegrambot_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='giveaway',
            name='requirement_type',
            field=models.CharField(choices=[('none', 'No Requirement'), ('manual_approval', 'Manual Verification (Screenshot/Proof)'), ('phone_number', 'Mobile Number Verification')], max_length=20),
        ),
    ]
