# Generated by Django 4.2.27 on 2026-01-24 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('giveaway_engine', '0004_telegramuser_phone_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AlterField(
            model_name='giveaway',
            name='requirement_type',
            field=models.CharField(choices=[('none', 'No Requirement'), ('manual_approval', 'Manual Verification (Screenshot/Proof)'), ('questionnaire', 'Questionnaire (Answer Questions)')], max_length=20),
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='giveaway_engine.questionnaire')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='giveaway_engine.telegramuser')),
            ],
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='giveaway',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='giveaway_engine.giveaway'),
        ),
    ]
