# Generated by Django 4.2.27 on 2026-01-25 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giveaway_engine', '0005_questionnaire_alter_giveaway_requirement_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegrambot',
            name='webhook_domain',
            field=models.URLField(blank=True, help_text='Base URL for webhook (e.g. https://domain.com)', null=True),
        ),
    ]
