# Generated by Django 4.2.27 on 2026-01-25 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giveaway_engine', '0006_telegrambot_webhook_domain'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='giveaway',
            options={'ordering': ['sequence']},
        ),
        migrations.AddField(
            model_name='giveaway',
            name='failure_message',
            field=models.TextField(blank=True, help_text='Message sent if prerequisites not met', null=True),
        ),
        migrations.AddField(
            model_name='giveaway',
            name='pre_giveaway',
            field=models.PositiveIntegerField(blank=True, help_text='Must claim all giveaways with sequence <= this value first', null=True),
        ),
        migrations.AddField(
            model_name='giveaway',
            name='sequence',
            field=models.PositiveIntegerField(default=1, help_text='Order of display and claim number'),
        ),
        migrations.AlterUniqueTogether(
            name='giveaway',
            unique_together={('bot', 'sequence')},
        ),
    ]
