# Generated by Django 4.2.27 on 2026-01-26 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giveaway_engine', '0007_alter_giveaway_options_giveaway_failure_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='giveaway',
            name='follow_up_text',
            field=models.TextField(blank=True, help_text='Sent automatically after fulfillment', null=True),
        ),
        migrations.AddField(
            model_name='giveawayattempt',
            name='follow_up_sent',
            field=models.BooleanField(default=False),
        ),
    ]
