# Generated by Django 4.2.27 on 2026-01-26 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('giveaway_engine', '0008_giveaway_follow_up_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='giveaway',
            name='failure_message',
        ),
        migrations.AddField(
            model_name='giveaway',
            name='failure_template',
            field=models.ForeignKey(blank=True, help_text='Template used when prerequisites not met', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='failure_tags', to='giveaway_engine.messagetemplate'),
        ),
    ]
