# Generated by Django 4.2.27 on 2026-01-26 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('giveaway_engine', '0009_remove_giveaway_failure_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='giveaway',
            name='prompt_template',
            field=models.ForeignKey(blank=True, help_text='Template used to ask for proof', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prompt_tags', to='giveaway_engine.messagetemplate'),
        ),
        migrations.AddField(
            model_name='giveaway',
            name='success_template',
            field=models.ForeignKey(blank=True, help_text='Template used when proof is received', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='success_tags', to='giveaway_engine.messagetemplate'),
        ),
    ]
