# Generated by Django 4.2.27 on 2026-01-27 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('giveaway_engine', '0010_giveaway_prompt_template_giveaway_success_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('direction', models.CharField(choices=[('inbound', 'Inbound (User -> Bot)'), ('outbound', 'Outbound (Bot -> User)')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='giveaway_engine.telegrambot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='giveaway_engine.telegramuser')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
