# Generated by Django 4.2.27 on 2026-01-30 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giveaway_engine', '0011_messagelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegrambot',
            name='start_message_header',
            field=models.TextField(default='🎁 Active Giveaways:', help_text='Text displayed above the list of giveaways in the /start message.'),
        ),
    ]
