# Generated by Django 4.2.27 on 2026-01-30 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giveaway_engine', '0012_telegrambot_start_message_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='giveaway',
            name='follow_up_delay_seconds',
            field=models.PositiveIntegerField(default=60, help_text='Seconds to wait after approval before sending the follow-up message.'),
        ),
    ]
