# Generated by Django 4.2.27 on 2026-02-03 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giveaway_engine', '0013_giveaway_follow_up_delay_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='giveaway',
            name='allow_retake',
            field=models.BooleanField(default=False, help_text='If checked, users can retake the questionnaire even if they have already claimed the giveaway.'),
        ),
    ]
