# Generated by Django 4.2.27 on 2026-02-04 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giveaway_engine', '0014_giveaway_allow_retake'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
